service: ${file(./config.${self:custom.currentStage}.json):serviceName} 

custom:
  defaultStage: prod
  currentStage: ${opt:stage, self:custom.defaultStage}
  currentRegion: ${file(./config.${self:custom.currentStage}.json):region}

provider:
  name: aws
  runtime: nodejs6.10
  region: ${self:custom.currentRegion}
  stage: ${self:custom.currentStage}

functions:
  hello:
    handler: handler.hello
